#ifndef LASERLINE_STATES_H
#define LASERLINE_STATES_H

enum LaserStates {
  CYCLE_ON_START,
  CYCLE_ON_WAIT,
  CYCLE_ON_END,
  CYCLE_OFF_START,
  CYCLE_OFF_WAIT,
  CYCLE_OFF_END,
  
  COMMAND_ON,
  COMMAND_LISTEN,
  COMMAND_OFF,
  COMMAND_FREQUENCY,
  COMMAND_DUTYCYCLE,

  MOMENTARY_ON,
  MOMENTARY_OFF,
};

#endif// LASERLINE_STATES_H